### ISSUE TITLE
Update `stopDockerService` method to work on Linux and Windows

### ISSUE THREAD

**Issue by mattstauffer** [tighten/takeout#112]
Current version is clearly (and knowingly) macOS only:

```php
    public function stopDockerService(): void
    {
        $this->shell->execQuietly("test -z $(docker ps -q 2>/dev/null) && osascript -e 'quit app \"Docker\"'");
    }
```

**Comment by ThirumlaDevi** [comment]
@mattstauffer I was able to stop docker service running in my machine with a piped shell command without the use of /dev/null file (linux dependency) and osascript(mac dependency). 
i am positive that i will be able to solve this issue for you and I would like to help you with this, can you please assign this issue to me ?

**Comment by mattstauffer** [comment]
@ThirumlaDevi Sounds great!

**Comment by ThirumlaDevi** [comment]
@mattstauffer I was able to successfully install and use Takeout tool
However I am facing issues when building the application ( without applying my changes ) as specified in the [process-for-release](https://github.com/tighten/takeout#process-for-release) section of the readme.
I have attached the error that i am getting while building the project. What i could infer is that the target .phar file is not getting created
`php ./takeout app:build

                                                
                Building process                
                                                

 Build version? [unreleased]:
 > 1.4.0

   1. Moving application to production mode: ✔
   2. Compile into a single file: ✔


   ErrorException 

  rename(/Users/thirumladevis/personal/project_1/takeout/takeout.phar,/Users/thirumladevis/personal/project_1/takeout/builds/takeout): No such file or directory

  at vendor/illuminate/filesystem/Filesystem.php:240
    236|      * @return bool
    237|      */
    238|     public function move($path, $target)
    239|     {
  > 240|         return rename($path, $target);
    241|     }
    242| 
    243|     /**
    244|      * Copy a file to a new location.

      +21 vendor frames 
  22  takeout:37
      LaravelZero\Framework\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

**Comment by ThirumlaDevi** [comment]
@mattstauffer I was able to successfully install and use Takeout tool
However I am facing issues when building the master application ( without applying my changes ) as specified in the [process-for-release](https://github.com/tighten/takeout#process-for-release) section of the readme.

With what i could infer is that the target takeout.phar file is not getting generated.
```
$php ./takeout app:build
 Building process                
                                                

 Build version? [unreleased]:
 > 1.4.0

   1. Moving application to production mode: ✔
   2. Compile into a single file: ✔


   ErrorException 

  rename(/Users/thirumladevis/personal/project_1/takeout/takeout.phar,/Users/thirumladevis/personal/project_1/takeout/builds/takeout): No such file or directory

  at vendor/illuminate/filesystem/Filesystem.php:240
    236|      * @return bool
    237|      */
    238|     public function move($path, $target)
    239|     {
  > 240|         return rename($path, $target);
    241|     }
    242| 
    243|     /**
    244|      * Copy a file to a new location.

      +21 vendor frames 
  22  takeout:37
      LaravelZero\Framework\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```
The following are the dependencies and it's corresponding versions that i have included as part of this project
- _Composer_ version 1.10.13
- _PHP_ version 7.4.10
- _PHPUnit_ version 8.5.8
- I am using a macOS system and i already have stable docker desktop installed in it
Can you please help me with this build error? Also if you want me to reach out to the takeout tool's team via some other means and not via comments as it might be a disturbance for other people visiting this issue, please do let me know

**Comment by mattstauffer** [comment]
@ThirumlaDevi Hm, I've never seen that. Do you have a file sitting in your directory named `takeout.phar`?

Either way, though, don't worry about the build; you can just test your changes using the `takeout` file that's in the root. I'll handle the builds. :)

**Comment by ThirumlaDevi** [comment]
@mattstauffer Will providing screenshots of how the shell commands ( as given in the above [PR](https://github.com/tighten/takeout/pull/150) )  executed in corresponding OS cmd lines , stops docker service, be helpful for the team? 
Please do let me know if the solution has solved your issue or how i can help :)
