### ISSUE TITLE
Default MySQL password

### ISSUE THREAD

**Issue by plakhin** [tighten/takeout#114]
Documentation lacks of information about username/password and database name that should be provided in .env file of Laravel app. Or some steps needed to login as root user, create db and user. Can you provide this information please?

**Comment by thecrypticace** [comment]
The MySQL password is provided / can be changed when enabling the mysql service. The default is `password`. There's no default database created. You'll need to connect using a database GUI and create one.

You can use the following details in your `.env` file (assuming you have used the defaults):
```
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=your_created_database_name_here
DB_USERNAME=root
DB_PASSWORD=password
```

**Comment by plakhin** [comment]
Thanks for response! Already found that settings. But it would be nice to have this in readme as takeout is positioned as a simple solution and my front-end dev wasn't able to set it up. Since I didn't see the first steps, it took some time to find out that default password.

**Comment by mattstauffer** [comment]
As of the latest version, the default password is now `null`, which mirrors Laravel's defaults. 

https://github.com/tighten/takeout/releases/tag/v1.3.0

**Comment by johanrosenson** [comment]
@mattstauffer What does it mean that the password is null? 

`What will the root password be? (null by default)`

I just got this question while enabling mysql , and I found it very confusing, is the password the string "null", or an empty string? or a null byte? only the empty string makes sense to me, but yeah, it's a confusing use of the word null :)

**Comment by mattstauffer** [comment]
@johanrosenson I'm not sure how MySQL treats it internally, but I believe there was some conversation about `null` being differently than an empty string when it comes to how we pass it. But I could be wrong. :)
