### ISSUE TITLE
Update GitHub Actions text matrix to test on Linux and Windows again

### ISSUE THREAD

**Issue by abenettt** [tighten/takeout#120]
Before going public the matrix was reduced to only test on macos to save build hours but as we're now public we could test on windows and linux again too as the build hours are unlimited for public repositories.

**Comment by mattstauffer** [comment]
Great call! Our tests don't have a lot of items that *actually* interact with the system; they mock most of that out.
But wouldn't hurt! Great call!

**Comment by mattstauffer** [comment]
https://github.com/tighten/takeout/blob/main/.github/workflows/run-tests.yml#L14

**Comment by mattstauffer** [comment]
https://github.com/tighten/takeout/blob/main/.github/workflows/run-tests.yml#L24
