### ISSUE TITLE
Port still in use after takeout disable mysql

### ISSUE THREAD

**Issue by voidgraphics** [tighten/takeout#122]
I had a problem with my mysql instance so I thought no problem, I'll just remove it and spin it back up. So naturally I ran `takeout disable mysql` and it removed it, but when I try to spin it back up immediately after, I can not use the same port that I was using before, as it complains that it it still in use. A reboot of my mac allows me to use the port again.

**Comment by jonsugar** [comment]
@voidgraphics did you have a database GUI (TablePlus or Sequel Pro etc) open? It could be holding the port.

From the FAQ:

> **If I disable a service but Takeout still shows the port as taken, how do I proceed?**
> First, run lsof -i :3306 (where 3306 is the port that's unavailable.)
>If you see output like this:
```
com.docke   936 mattstauffer   52u  IPv6 0xc0d6f0b06d5c4efb      0t0  TCP localhost:mysql->localhost:62919 (FIN_WAIT_2)
TablePlus 96155 mattstauffer   16u  IPv4 0xc0d6f0b0b6dccf6b      0t0  TCP localhost:62919->localhost:mysql (CLOSE_WAIT)
```
> The solution is to just close your database GUI, and then it should be released.

**Comment by voidgraphics** [comment]
Thanks for the tip, I was indeed running Sequel Ace. 

It seems having the Docker Dashboard open also keeps the port busy, but closing both of them works.

Thanks!
