### ISSUE TITLE
Add a passthrough command to run commands on Takeout-managed Docker instances

### ISSUE THREAD

**Issue by mattstauffer** [tighten/takeout#125]

**Comment by mattstauffer** [comment]
I'm thinking something like this:

```bash
takeout pt mysql mysql
```

This would allow me to run the `mysql` command on a Takeout-managed Docker instance which matches `mysql`.

As always, if two instances match `mysql` I'd have to pick which from a selector.

This would run:

```bash
docker exec -it TO--mysql--5.7 mysql"
```

We'd probably also want a non-interactive mode. We could either make a flag for that, *or* we could default to non-interactive and require a `-i` flag passed to be interactive. (Interactive mode, as I've learned from @josecanhelp, is toggled via the `-it` flag passed to `docker exec`).

**Comment by lacasera** [comment]
giving this a go
