### ISSUE TITLE
Use --default flag to enable many services using commands

### ISSUE THREAD

**Issue by khanalpride** [tighten/takeout#130]
I am sure everyone work with at least 2/3 services in a project.

I do use postgresql, redis, mailhog on all of my projects and to enable them it will take commands and then press enter for few times to enable a feature. and this process goes on if there are few of the services to enable.

How about having `--default` flag on enable command to use default ports/tag/version for a service and run command directly?

for example I have this on my alias and I just run `on` to enable them all at once
```
function on() {
    valet restart
    takeout enable postgresql --default
    takeout enable redis --default
    takeout enable mailhog --default
}
```

and yeah I disable them using off like this
```
function off() {
    valet stop
    takeout disable postgresql
    takeout disable redis
    takeout disable mailhog
}
```

@mattstauffer will you accept a PR if I send it? As I already have it working on my WSL2.

**Comment by mattstauffer** [comment]
@khanalpride Absolutely! @josecanhelp and I already talked about wanting this idea. :)

**Comment by khanalpride** [comment]
Its working all good. As by default all the services I use are available on different ports.
Only thing if port already enabled, the port checker normally always says port is available.
I am trying to figure it out.
After figuring it out, I will send PR.

**Comment by khanalpride** [comment]
Closing this as I have already made a PR here #133
