### ISSUE TITLE
Authenticating Postgres users with Laravel app?

### ISSUE THREAD

**Issue by connor11528** [tighten/takeout#140]
Hi first off wanted to say the project is really cool. Excited to use it! I was able to connect to Postgres takeout container with Table Plus but my Laravel app isn't able to connect from localhost. 

```
SQLSTATE[08006] [7] FATAL:  password authentication failed for user "postgres"
FATAL:  password authentication failed for user "postgres" (SQL: select * from "users" where ...
```
Pretty sure I'm using same values in my **.env** file:
```
DB_CONNECTION=pgsql
DB_HOST=localhost
DB_PORT=5433
DB_DATABASE=employbl
DB_USERNAME=postgres
DB_PASSWORD=password
```
Running Laravel 6. On the Postgres side when I go to the CLI for the takeout docker command we've created a database. Do we need to create users for the Postgres takeout container or do other things to connect the Laravel app to the Postgres database? Sorry if this better belongs on stackoverflow.

On the Postgres container:
```
docker exec -it d9b7c0857dc704bXXXXX6efc88fdc1baa8d1faf9d /bin/sh; exit
# psql -U postgres
psql (13.0 (Debian 13.0-1.pgdg100+1))
Type "help" for help.
postgres=# create database employbl;
CREATE DATABASE
postgres=# \deu+
      List of user mappings
 Server | User name | FDW options 
--------+-----------+-------------
(0 rows)
```
The database is there when used command `\l` to show the postgres databases. I guess just wondering best practice for connecting to the Postgres database from a Laravel application running on local computer? Any idea why we are getting `password authentication failed` for connecting to the postgres db?

**Comment by josecanhelp** [comment]
@connor11528 my apologies for the crazy late reply here. I have been using postgres locally on an app without issue. Are you still experiencing this?

**Comment by connor11528** [comment]
Hmm ya know it's not an issue for us anymore.. forget what we did though! We can close this issue and if it pops up again will let you know :)
