### ISSUE TITLE
Add category to service list JSON

### ISSUE THREAD

**Issue by mattstauffer** [tighten/takeout#143]
(See #88 and #135)

**Comment by danielebarbaro** [comment]
I was thinking about json output days ago, feel free to assign also this to me 🤓.
I can easily handle this feature.
maybe we could talk about the right format

**Comment by mattstauffer** [comment]
@danielebarbaro Sounds great! We actually already have JSON output, so this would be a quick one for you :)

**Comment by mattstauffer** [comment]
https://github.com/tighten/takeout/pull/111

**Comment by tonysm** [comment]
@mattstauffer I think we can close this one, right?

**Comment by mattstauffer** [comment]
Yup!

**Comment by mattstauffer** [comment]
Closed by #149.
