### ISSUE TITLE
Double-check all functionality works in Linux

### ISSUE THREAD

**Issue by mattstauffer** [tighten/takeout#144]
Per #37 we may be completely compatible with most Linux distros, but I'd love for Linux users to check it out for me.

Tag @jyrkidn, @PHLAK, and @sinnbeck who all commented on that issue about Linux.

**Comment by PHLAK** [comment]
I'll do my best to check this out in the next couple of days.

**Comment by jyrkidn** [comment]
I'm on Pop!_OS 20.04 LTS and can confirm that I can enable and disable docker containers through takeout. I'm going to start using it daily now, if i should encounter any issues, I'll create a new one.

**Comment by wsamoht** [comment]
I just tried on Linux Mint 20 and was able to start/stop and enable/disable a MySQL container with takeout.

**Comment by K03413R** [comment]
I'm using this on Ubuntu 20 and everything is working great.

**Comment by mattstauffer** [comment]
Thanks everyone! Gonna call this good!
