### ISSUE TITLE
Update app to work in Windows (non-WSL)

### ISSUE THREAD

**Issue by mattstauffer** [tighten/takeout#146]
See #37 (especially https://github.com/tighten/takeout/issues/37#issuecomment-701014533) for notes about @delta1186's work toward this effort.

**Comment by delta1186** [comment]
@mattstauffer first thing I am trying to tackle is the menu on the EnableCommand.  Would you prefer I share some code here or get to a stopping point and make a PR so you can review things and make recommendations there?

**Comment by delta1186** [comment]
I about to submit a PR.  I still need to write some OS specific tests, but I am pretty close I think.  I have updated the enable, disable, start and stop commands to support native Windows.  Here are some screen shots of how it will look in cmder and the cmd prompt which have a light and dark theme.  

### Enable Menu
This is menu has one additional feature not available in the default menu which is when you select a category the list is filtered down to just those items.  You then have the option to go back or exit from there.  
![image](https://user-images.githubusercontent.com/421307/96132641-417aab00-0ec0-11eb-86d5-7aedef5a5582.png)
### Disable Menu
This menu just works like the default menu where you select an item and the container is disabled and the menu automatically exits.
![image](https://user-images.githubusercontent.com/421307/96133633-97e7e980-0ec0-11eb-8250-adf6561c31ef.png)
### Start and Stop Menus
These menus work the same as the default menu.  When you start or stop one, then the menu will reload with remaining containers and on the start or stop of last available container the command will exit automatically.
![image](https://user-images.githubusercontent.com/421307/96131327-a8976000-0ebe-11eb-8828-1c371b7b7d93.png)
![image](https://user-images.githubusercontent.com/421307/96131416-c06ee400-0ebe-11eb-933d-52f7b5d57197.png)
![image](https://user-images.githubusercontent.com/421307/96131757-35dab480-0ebf-11eb-8887-edf8e6b35a51.png)
