### ISSUE TITLE
add ClickHouse support

### ISSUE THREAD

**Issue by plakhin** [tighten/takeout#158]
Please add ClickHouse support.
https://hub.docker.com/r/yandex/clickhouse-server/

**Comment by K03413R** [comment]
@plakhin  I made a branch if you want to check it out. https://github.com/K03413R/takeout.git

**Comment by grantjanecek** [comment]
@mattstauffer  This can be closed. Pr #159 added this.

**Comment by mattstauffer** [comment]
hanks @grantjanecek!
