### ISSUE TITLE
Add SFTP server support

### ISSUE THREAD

**Issue by chrisdicarlo** [tighten/takeout#165]
Hi,

I've built a custom service to allow spinning up SFTP servers using the atmoz/sftp image in my fork, just wondering if it would be of any interest to anyone for inclusion as a service in Takeout?

It currently supports:

- defining the port
- defining the SFTP user and password
- modifying the internal directory name on the server
- mapping a host directory into the container directly

I've got it working fine on my local takeout build.  More than happy to submit a PR if it's useful to anyone!

Cheers,
Chris

**Comment by mattstauffer** [comment]
@chrisdicarlo Thanks for the issue! So this allows external folks to SFTP into your local machine, given your public IP? If so, this is definitely interesting!

**Comment by chrisdicarlo** [comment]
@mattstauffer Actually, it was more for me to be able to spin up SFTP servers locally that can be used for testing, etc.  But your idea is interesting - just not sure how it could work consistently while still being local, i.e. without mucking about with any external firewall policies or port forwards.

I wonder if you could leverage Expose to tunnel it through somehow?  That would require a self-hoseted Expose server (another possible feature? :grin: ) but you could have the policies/forwards preset to point to it - but they would only be effective when you have actually spun up the Expose server?

**Comment by chrisdicarlo** [comment]
Actually, I think even with Expose you would need to add a reverse proxy at the front end or a firewall policy / port forward anyway.  Either way will require some level of changes at the edge of the network.

If you have to do that anyway, you could simply have it point at the SFTP container directly.
