### ISSUE TITLE
Self-hosted Expose server

### ISSUE THREAD

**Issue by chrisdicarlo** [tighten/takeout#166]
Hi,

Opening an issue about possibly adding an option to have a self-hosted Expose server added as a service.  I have a working setup and would be more than willing to submit a PR.

There are some additional steps that need to be performed for the whole thing to work, e.g.:

- Create a wildcard DNS record for the TLD
- Configure the reverse proxy to forward traffic for the above domain(s) to the IP of the device hosting the Expose container

As part of my set up, I added a "Tools" category for the menu entry as this doesn't really fit nicely into any of the existing categories.  I can split that into a separate PR, if needed.

Any thoughts on this more than welcome!

Cheers,
Chris

![image](https://user-images.githubusercontent.com/3483368/96373166-a8a29480-1138-11eb-9a6e-012d0f0149f0.png)
![Screenshot from 2020-10-18 11-55-10](https://user-images.githubusercontent.com/3483368/96373198-e99aa900-1138-11eb-9c93-8352fddedffe.png)

**Comment by mattstauffer** [comment]
@chrisdicarlo Certainly interesting! I guess this will be our first one that won't work unless you *also* do other work, but yah, this sounds like a great idea!

**Comment by chrisdicarlo** [comment]
@mattstauffer yeah, but I kind of envisioned it being for people that typically work from the same device and want to provide access for a client to take a peek so you kind of set up the DNS and forwarding stuff once and then just spin up the server we need to expose (no pun intended) the site￼.
