### ISSUE TITLE
Support for Open Distro for Elasticsearch as a Service

### ISSUE THREAD

**Issue by Goldyberg** [tighten/takeout#169]
Open Distro for Elasticsearch https://opendistro.github.io/for-elasticsearch/ stems from AWS. They use it for their managed AWS service https://aws.amazon.com/elasticsearch-service/. 

Although there is large feature overlap with Elastic's offering. There are differences when it comes to plugins and some implementation details.

Version mapping: https://opendistro.github.io/for-elasticsearch-docs/version-history/
Docker documentation: https://opendistro.github.io/for-elasticsearch-docs/docs/install/docker/

Potential quirk if you're used to using https://github.com/elastic/elasticsearch-php to connect
https://github.com/opendistro/for-elasticsearch-docs/issues/22.

**Comment by josecanhelp** [comment]
This may require a new service so we could avoid image overlap. Please add this as a new container request here: https://github.com/tighten/takeout/discussions/224
