### ISSUE TITLE
Fix `list` being too wide

### ISSUE THREAD

**Issue by mattstauffer** [tighten/takeout#173]
Since the networking feature has been implemented, the list command's output is too wide on many screens:

![image](https://user-images.githubusercontent.com/151829/98564081-ed25d980-2279-11eb-98ad-bc6e76974019.png)

We mayyy want to do something like `--networking` as a flag that adds the alias and base alias?

**Comment by danielebarbaro** [comment]
I can use a couple of hours out of my usual open source time in order to manage this and #174.
Since I really love this package, i can even use more then 2 hours 🤓 😎

**Comment by mattstauffer** [comment]
Awesome--thanks @danielebarbaro!!

**Comment by josecanhelp** [comment]
This may not be relevant enough since we are porting to node. Oclif manages the output a little better than symfony tables.
