### ISSUE TITLE
Redis Undefined offset: 1

### ISSUE THREAD

**Issue by K2ouMais** [tighten/takeout#177]
Hello,

I am using WSL2 and I am getting an error when enabling Redis.

![redis](https://user-images.githubusercontent.com/52510455/98597327-280b2a00-22d9-11eb-968c-91753f155249.png)

Am I doing something wrong?

Thanks in advance

**Comment by reed-jones** [comment]
I'm having this same error on macOS trying to enable Redis & MariaDB

**Comment by mattstauffer** [comment]
@reed-jones @K2ouMais Should be fixed now. Thanks!
