### ISSUE TITLE
Local Jenkins automation image

### ISSUE THREAD

**Issue by wotta** [tighten/takeout#186]
First off thank you for creating this tool. It has helped me a lot in the last few months.

I wondered about adding a local Jenkins image for local automation testing.
The reason why this could be interesting to provide the option is that you might want to test your application before it hits an external CI/CD platform.

For example, It could be beneficial if you run an internal "automation" service before your push towards Bitbucket.
Bitbucket isn't always that stable so the option to make sure your feature works before hitting the external platform could be really helpful.

Could this be an image that would benefit other developers?

**Comment by josecanhelp** [comment]
This is absolutely an image some developers would find useful. If you'd like to ask the community for help making a Takeout container, post your request here: https://github.com/tighten/takeout/discussions/224
