### ISSUE TITLE
Add Support for PHP 8

### ISSUE THREAD

**Issue by alextpritchard** [tighten/takeout#187]

**Comment by pmayet** [comment]
https://github.com/tighten/takeout/pull/188

**Comment by pmayet** [comment]
@mattstauffer It is possible to publish a new release with the php8 compatibility ?

**Comment by mattstauffer** [comment]
@pmayet Apologies!

**Comment by mattstauffer** [comment]
https://github.com/tighten/takeout/releases/tag/v1.6.5
