### ISSUE TITLE
MySQL said: Host '172.18.0.1' is not allowed to connect to this MySQL server

### ISSUE THREAD

**Issue by stevieegee** [tighten/takeout#190]
I enable MySQL 8.0 port 3306 or 3308 and MySQL 5.7 port 3307. Both work fine until I restart my Mac. Then with MySQL 8.0 is get the error - MySQL said: Host '172.18.0.1' is not allowed to connect to this MySQL server. MySQL 5.7 is alway fine just 8.0. I have deleted them and their volumes and recreated them in a different order but 8.0 always gives me the same error.

**Comment by stevieegee** [comment]
The problem with MySQL 8.0 seems to be due to importing multiple database. If I  mysql -u root -p --host='127.0.0.1' --port=3306 < all_db.sql , it imports all the dbs and works fine, but if I restart the container I get the error.

**Comment by mattstauffer** [comment]
@stevieegee that's very strange. Are you still seeing this error? Thanks!

**Comment by mabadir** [comment]
@mattstauffer I am seeing that error as well. This happens usually while Docker is spinning the container. Once it's fully operational the error goes away.

**Comment by mattstauffer** [comment]
OK, that makes sense. Database doesn't connect while it's restarting? Is anyone seeing it any other times?

**Comment by MarceauKa** [comment]
Got the same error after a takeout + docker reinstallation. When I sshed into the container, I can't execute a simple `mysql -u root -p`. So locally and remotly I am unable to use my container

**Comment by josecanhelp** [comment]
This seems like an issue with the container service not having enough time to get to a healthy state before trying to access the service. In the node port of takeout, we will be implementing a listener to check the health state before allowing interaction with the service.
