### ISSUE TITLE
Laravel 8 - Migrate Squash / Mysqldump missing 

### ISSUE THREAD

**Issue by Jarrid** [tighten/takeout#199]
Hi!

## Issue:
When running mysql 5.7 in a docker using takeout, I cannot squash migrations into a single .sql file per the php artisan schema:dump.  The error I receive is "mysqldump command not found".  I get why it's occurring  - that MySQL is not installed in my system, but within Docker, and thus not in my /bin/ path to be executed.

I have run mysqldump directly from my machine (in DataGrip) and then placed that into the schemas folder.
I moved my migrations to an "old" folder, and ran migrate:fresh.  Laravel found the schema (as expected), but it threw another error "mysql command not found" - which I assume is the exact same issue as above.

## Question:
Have I missed something in regards to this specific piece?  Is anyone else using takeout and performing the squash / migrate?  Takeout is definitely awesome - but I feel like I might be making this process more difficult than if I had just installed MySQL through Homebrew?

**Comment by mabadir** [comment]
I am using `schema:dump` with Takeout on MySQL v8 though. You need to have the MySQL client installed on your machine, and it will access the database on the Docker container and dump the schema.

**Comment by josecanhelp** [comment]
@Jarrid the artisan command checks for a local instance of the mysql command, and if you are using docker, this is not available. You can install mysql locally to make the binary available. This is less than ideal, but I'll try to think of some more creative ways to eventually get this working.

**Comment by jasonvarga** [comment]
Sorry to comment on an old issue, but has anyone come up with a solution in the last couple of years? 😄

**Comment by stevepop** [comment]
I am having this same problem. Can't believe this issue has been pending since 2020 🤷
