### ISSUE TITLE
Dependency Injection

### ISSUE THREAD

**Issue by delta1186** [tighten/takeout#200]
I am wondering if the start, stop, enable, and disable commands should be standardize with some injected dependencies.  This will avoid some work arounds with testing I had to implement in order to handle a class is not tied to the command, but rather directly loaded from the container.  Hope I am saying that right. :)  Like the following example from line [63](https://github.com/tighten/takeout/blob/0ac5975aac8843330428163267acb60b5d609552/app/Commands/StartCommand.php#L63) in StartCommand.

`app(Docker::class)->startContainer($container)`

I would like to implement constructor injection for Docker, Environment, and also Services for some commands.  It is already being done to some scale in the commands.  Some something like this.

```
   protected $description = 'Start a stopped container.';
    protected $docker;
    protected $environment;

    public function handle(Docker $docker, Environment $environment): void
    {
        $this->environment = $environment;
        $this->docker = $docker;
        $this->initializeCommand();
```

This would prevent me from having to add the following to some of the tests to get them to run in all of the required php versions.

```
/** @test
     * @runInSeparateProcess
     * @preserveGlobalState disabled
     */
```

@mattstauffer or @josecanhelp let me know if you are okay with this and I can make a PR for it.  

This won't stop me from finishing my tests for Windows menus, so I am fine either way.  If you do want to do this later, then I can just refactor my tests if that PR is already merged as part of this PR.  Just wanted to make the suggestion now.

**Comment by mattstauffer** [comment]
@delta1186 Sounds good to me! Thanks!!

**Comment by delta1186** [comment]
Hey @mattstauffer I am working on a PR for this and before submitting I was trying to figure out why your Actions were failing for php7.2.  I appears that PHPUnit 9 that you moved to no longer supports Php 7.2.  Do you want to remove 7.2 support or rollback PHPUnit?

**Comment by mattstauffer** [comment]
@delta1186 Thanks--I'd like to eventually bring that support back in via a PHPUnit bridge command, but you can comment out 7.2 support for now. Thanks!
