### ISSUE TITLE
Discussion: Should we add a port sniffer?

### ISSUE THREAD

**Issue by mattstauffer** [tighten/takeout#208]
I've occasionally run into the situation where I'm told a port I want to use is in use:

![image](https://user-images.githubusercontent.com/151829/105363650-455a4f80-5bca-11eb-9374-5a85df89fe42.png)

But I can *never* remember the command to look that information up.

I know it's not quite Takeout's domain, but I also know a lot of people like me who use Takeout don't remember the netstat-or-whatever-else command.

What do y'all think about adding a quick command like `takeout whichport 1025` or something?

**Comment by mabadir** [comment]
I would like the error message in red in your screenshot to tell me which service is using it, so I can stop it.

**Comment by mabadir** [comment]
We will need different implementations though for each OS (macOS, Linux and Windows).

**Comment by josecanhelp** [comment]
This is currently working and also being ported over to the node version.
