### ISSUE TITLE
Connection refused trying to connect to registry-1.docker.io

### ISSUE THREAD

**Issue by mattstauffer** [tighten/takeout#209]
I know I'm a Takeout maintainer so I don't have to make this public, but I figure I'm not the only person who'll ever see this error, so I'll put it here publicly while I try to figure it out.

![image](https://user-images.githubusercontent.com/151829/105366897-dd0d6d00-5bcd-11eb-8ac4-922aaf784756.png)

```
 ERR  Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.64.1:53: read udp 192.168.64.2:36267->192.168.64.1:53: read: connection refused
```

This is on an m1 laptop using the brand new Docker for desktop build, so first thing I'm going to do is install a Docker container the classic way not using takeout and I bet I'll have the same issue there. :)

**Comment by mattstauffer** [comment]
Yuuuuup.

![image](https://user-images.githubusercontent.com/151829/105367069-0b8b4800-5bce-11eb-88dc-6b1588804328.png)

Not a takeout issue, but when I find the solution I'll put it here anyway. :)

**Comment by mattstauffer** [comment]
These folks said restarting Docker fixed it, but sadly that didn't work:

https://forums.docker.com/t/error-response-from-daemon-get-https-registry-1-docker-io-v2/23741/26

Gonna try restarting my computer next just for fun. :)

**Comment by mattstauffer** [comment]
Restarting did not fix it. :/

**Comment by dennisvandalen** [comment]
@mattstauffer try stopping the dnsmasq service

**Comment by mattstauffer** [comment]
@dennisvandalen Thanks! Sadly that didn't work. Interestingly my dnsmasq services *was* in an error status, but stopping it didn't fix the problem.

**Comment by mattstauffer** [comment]
Thought it might be DNS related so I tried this, but no luck:

![image](https://user-images.githubusercontent.com/151829/105638521-03870e80-5e41-11eb-816e-e7b881e3ae0c.png)

**Comment by jasonvarga** [comment]
I'm running into it, also running an M1. Here's the docker issue: https://github.com/docker/for-mac/issues/5186

At least for me, the workaround is this, in this order:

- stop dnsmasq
- restart docker for mac
- takeout enable whatever should run fine

After you've enabled the container, you can turn dnsmasq back on.
Running takeout start/stop seems to be fine without needing to disable dnsmasq once you've enabled the container.

**Comment by mattstauffer** [comment]
@jasonvarga Thank you! I tried stopping DNSMasq and it didn't work, but I'm gonna stop it and restart the machine shortly and test that out. Thank you for the link, too!

**Comment by hcancelik** [comment]
> @jasonvarga Thank you! I tried stopping DNSMasq and it didn't work, but I'm gonna stop it and restart the machine shortly and test that out. Thank you for the link, too!

You just need to restart the docker after stopping dnsmasq. Also, double check that it's indeed stopped instead of failed.

**Comment by mattstauffer** [comment]
@hcancelik You're right! I had tried to restart it in the preferences, using "apply and restart" on some changes I was making, but that apparently didn't cut it; I actually had to click on the dropdown and click Restart, and then that fixed it.

Thanks!

<img width="243" alt="image" src="https://user-images.githubusercontent.com/151829/105754676-5aabe280-5f18-11eb-9b11-b2d16f9f4b43.png">

**Comment by mattstauffer** [comment]
Thanks again @jasonvarga!

For anyone else who runs into this, this is a Docker for Mac  + DNSMasq (likely installed by Laravel Valet) thing, not a Takeout thing. 

https://github.com/docker/for-mac/issues/5186

**Comment by zatorck** [comment]
It's also worth to say that it's not only issue caused by dnsmasq. Also when You restart container with dnsmaqs turned on Docker cannot read date properly and set dates as 1970 in its containers.

**Comment by dangoriya** [comment]
**user$** docker run hello-world
Unable to find image 'hello-world:latest' locally
docker: Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp 54.236.113.205:443: connect: connection refused.
**user$** curl https://registry-1.docker.io/v2/
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":null}]}

what might be the issue ?

**Comment by nerazzurri0302** [comment]
reboot turns ok.

**Comment by kehindeoderinde** [comment]
> Yuuuuup.
> 
> ![image](https://user-images.githubusercontent.com/151829/105367069-0b8b4800-5bce-11eb-88dc-6b1588804328.png)
> 
> Not a takeout issue, but when I find the solution I'll put it here anyway. :)

**Comment by moosasharieff** [comment]
I faced this error when running Docker Engine using [colima](https://github.com/abiosoft/colima) 

Just after restarting colima, by executing command: `colima restart`, I was able to push my Docker image on the DockerHub.
