### ISSUE TITLE
Install latest version of Postgres?

### ISSUE THREAD

**Issue by edalzell** [tighten/takeout#213]
I enabled postgres and chose `latest`, but it pulled down version 10, whereas docker has up to version 13. It would be great if the 'latest' was at least what is installed by Forge, which I believe is version 12.

How can I help implement this? I took a browse through the code but didn't immediately see where the versions were retrieved.

Thanks

**Comment by mattstauffer** [comment]
Hey @edalzell!

This may be similar to https://github.com/tighten/takeout/issues/207... it looks like the author of that issue had a solution, and said they were going to PR it, but didn't, so if you're up to help, maybe you can make that PR?

Thanks!

**Comment by edalzell** [comment]
I'll take a look and see if I can figure it out.

**Comment by edalzell** [comment]
Hey @mattstauffer, got a PR in for this, should address this issue and #207.

Looks like we need to sort the version "naturally".
