### ISSUE TITLE
install takeout on an Mac mini M1 

### ISSUE THREAD

**Issue by SimonJ** [tighten/takeout#215]
I have some issues trying to install takeout on a new Mac mini M1. 

I have followed the steps in the readme and installed the Apple M1 Tech preview docker version.
But when i run `takeout enable mysql` and just using the default version it fails with this.

Anyone know what the issue can be?

```
 OUT  8.0.23: Pulling from library/mysql
 ERR  no matching manifest for linux/arm64/v8 in the manifest list entries
Enabling mysql...

 ERR  Unable to find image 'mysql:8.0.23' locally
 ERR  8.0.23: Pulling from library/mysql
 ERR  docker: no matching manifest for linux/arm64/v8 in the manifest list entries.
 ERR  See 'docker run --help'.

Failed installing mysql
```

https://user-images.githubusercontent.com/183790/107491496-81f6e680-6b8b-11eb-8b88-10187e70f569.mov

**Comment by mattstauffer** [comment]
@SimonJ There's no MySQL build for the latest docker yet. You'll have to temporarily switch to MariaDB

**Comment by SimonJ** [comment]
Thanks @mattstauffer and then i need to install php with Brew, right?

**Comment by mattstauffer** [comment]
@SimonJ Yup!

**Comment by sperelson** [comment]
@mattstauffer Not sure of the scope, but wondering if being able to decide to use `--platform linux/amd64` for the Docker Pull might be useful as an option when deciding to enable an image. Even if there is an M1 version, choosing the x86 version may be useful.

It is pretty Mac M1 specific though and of limited appeal, probably.

**Comment by josecanhelp** [comment]
@sperelson I just read that Docker on M1 is finally available as GA, but there is still an issue with the mysql images for arm64: https://docs.docker.com/docker-for-mac/apple-silicon/

I'll close this ticket for now. Thanks!
