### ISSUE TITLE
Is there a way to override mysql config flags 

### ISSUE THREAD

**Issue by swilla** [tighten/takeout#217]
Is there a way to add some custom settings to the my.cnf or pass some arguments to the run command to bump up that setting? 

For example:
```
docker run -it -e MYSQL_ROOT_PASSWORD=my-secret-pw mysql:5.7 --max-allowed-packet=67108864
```

**Comment by josecanhelp** [comment]
At the moment, this is not possible. However, we are looking into that possibility. We will track this feature request at #218 .
