### ISSUE TITLE
Pass custom docker run parameters when enabling a service

### ISSUE THREAD

**Issue by wunc** [tighten/takeout#218]
I would love to have the ability to pass additional arbitrary custom docker run parameters to the services when initially enabling them. For example:

- For the MySQL container, pass `-e TZ=America/Chicago` to set the timezone via an environment variable
- To auto-restart a container when docker starts, pass `--restart unless-stopped`

I'm envisioning a simple text prompt in the enable menu after all the other service-specific prompts, where you can type in any additional custom parameters. These just then get inserted into to the docker run template after the other build parameters. Looking at how Takeout is structured, I don't think this would be too hard to implement, and it would go a long way in making it more versatile and giving people a simple persistent workaround to controlling various docker features.

Another even simpler option would be to just echo out the docker run command used when enabling a service, so that one could re-run it manually and tack on whatever else they wanted. Or maybe that could be disabled by default but available as an option via a Takeout verbosity config setting or cli parameter.

#189 is related, but I think slightly different in that they're asking for a non-menu-driven way of enabling Takeout-managed containers.

**Comment by mattstauffer** [comment]
I think this would be a great idea. I think the first and easiest solution would be adding a `--dry-run` flag to the `enable` command which allows you to copy what it's *going* to do and then modify it. But I do like the idea of finding a way to pass custom parameters!

**Comment by billmn** [comment]
I need to override the "innodb_strict_mode" for MariaDB, I think the ability to pass custom parameters to a container could be very useful.

Could also be very useful the ability to persist this parameters to a "per-container" file to override container config even after a reboot.

**Comment by mattstauffer** [comment]
@josecanhelp what do you think about this? I know you've been working hard to keep our prompts as simple as possible. Is it possible we make this a power user mode that can be configured so most users don't interact with it?

**Comment by josecanhelp** [comment]
Yea, I think a "mode" switch would be really nice so we can keep things simple for most users. But we also want to make it discoverable. 🤔

**Comment by rognales** [comment]
Would love this feature!

**Comment by mattstauffer** [comment]
I'm back to thinking about this feature.

Things I've thought about:

```
takeout enable --params
```

Then when you're filling out the prompts to spin up the container, you'll get an additional prompt:

```
What additional parameters would you like to pass to `docker run`? (e.g. `--restart unless-stopped`)
> 
```

or something like this:

```
takeout enable --params="--restart unless-stopped"
```

Any thoughts, preferences, other ideas?

**Comment by mattstauffer** [comment]
@thecrypticace suggests:

```bash
takeout enable -- (your params here)
```

e.g.

```bash
takeout enable -- --restart unless-stopped
```

**Comment by mattstauffer** [comment]
@jakebathman also is on board--pointed out that this is common for Yarn and Composer. I think it's settled.

Now... to code it!

**Comment by mattstauffer** [comment]
One suggestion for how to possibly handle `--`, from Geoff Selby:

https://twitter.com/geoff_selby/status/1543059001818103808

https://stackoverflow.com/a/71281329

**Comment by mattstauffer** [comment]
@wunc @billmn @rognales If any of y'all have a moment, would you test out this PR for me?

https://github.com/tighten/takeout/pull/294

Sample syntax:

```bash
./takeout enable meilisearch -- --your-flags-here
```

**Comment by rognales** [comment]
Hi @mattstauffer, i ran this command

```
php builds\takeout enable mariadb -- -e MARIADB_USER=zaiman -e MARIADB_PASSWORD=noris
````

But i got this error

```
Service enabled!

ERR  Service -e is invalid.
```

**Comment by mattstauffer** [comment]
@rognales Oh, sorry! I hadn't committed a build, so it would've needed to be `./takeout enable`.

I pushed this feature out as `v2.1.0`; would you mind testing it out?

https://github.com/tighten/takeout/releases/tag/v2.1.0

**Comment by modstore** [comment]
I'm not sure if I'm doing something wrong, but I couldn't get this to work.
```takeout enable elasticsearch -- -e "xpack.security.enabled=false"```
gives me this error:
```ERR  docker: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "-e": executable file not found in $PATH: unknown.```
