### ISSUE TITLE
Feature request - Grafana

### ISSUE THREAD

**Issue by leewillis77** [tighten/takeout#229]
It would be great to have support for [grafana](https://github.com/grafana/grafana) through takeout.

**Comment by josecanhelp** [comment]
Thanks for the suggestion, @leewillis77. 

Grafana seems like a cool project, but very complex. I don't have enough knowledge in some sensible defaults to write the feature myself. 

You can post the suggestion in our discussion forum to see if anyone with some deeper Grafana knowledge would be able to contribute: https://github.com/tighten/takeout/discussions/224
