### ISSUE TITLE
Fixed colors from enable are hard to use with Solarized Light

### ISSUE THREAD

**Issue by driesvints** [tighten/takeout#235]
I'm using Solarized Light as a terminal theme and the current fixed colors from `takeout enable` make it quite hard to use it in combination with that theme. I realize you can't account for every theme out there but Solarized Light is a very popular one. Even so, feel free to dismiss this!

![Screen Shot 2021-07-05 at 11 24 15](https://user-images.githubusercontent.com/594614/124449792-16085b00-dd84-11eb-98f7-444658b00c1f.jpg)

**Comment by tpetry** [comment]
The same for dracula:

<img width="862" alt="Bildschirmfoto 2021-07-05 um 15 42 03" src="https://user-images.githubusercontent.com/315686/124480485-97bdb000-dda7-11eb-853f-6cf93e3acb0e.png">

**Comment by mattstauffer** [comment]
Thanks for the heads up!!

As far as I can tell, we're not customizing the colors at all:

https://github.com/tighten/takeout/blob/2ab35c848b35d1867cef48513b0e9168280866a8/app/Commands/EnableCommand.php#L59-L73

Have you run into this same issue on any other projects that use Symfony's `menu` tooling? If not, I may make a base project with JUST symfony commands and see if I can repro. Thanks!

**Comment by driesvints** [comment]
Just checked into this again and this seems to be trickling down from https://github.com/nunomaduro/laravel-console-menu to https://github.com/php-school/cli-menu which uses this default color it seems. But I'm unsure how to proceed because if you'd adjust the color to our use cases then it most likely will cause an issue with other terminal setups. 

It would be great if the default terminal color would auto-adjust on the given theme but I don't know enough about terminal based output to know if that's possible or how to do that. In any case I think this issue can be closed because it's not specific to Takeout.

**Comment by mattstauffer** [comment]
Ahhhh, thanks!
