### ISSUE TITLE
Request for Mysql to use mysql/mysql-server to support linux/arm64/v8

### ISSUE THREAD

**Issue by yob-yob** [tighten/takeout#238]
This is the [docker-hub link to mysql-server](https://hub.docker.com/r/mysql/mysql-server/tags?page=1&ordering=last_updated) 

this is the [docker-hub link to mysql docker official image](https://hub.docker.com/_/mysql?tab=tags&page=1&ordering=last_updated)

here is a [stackoverflow link comparing both services](https://stackoverflow.com/questions/44854843/docker-is-there-any-difference-between-the-two-mysql-docker-images)

this would probably solve issues with Apple Silicon

**Comment by claudiodekker** [comment]
For what it's worth, using `mariadb` instead works just fine on AARM64 👍
