### ISSUE TITLE
Do we want beta/etc. to show up for "latest" tag?

### ISSUE THREAD

**Issue by mattstauffer** [tighten/takeout#246]
I just got `14beta2-buster` as a `latest` tag and I was wondering whether we actually want that?

It's from `postgres`.

Also, they have things like `14beta2-alpine3.14`, `14beta2-alpine`, and `14beta2-buster`, so I am wondering if we need to find a way to better nuance (for some, at least) which resolves as "latest"? I wouldn't even begin to know which to pick

**Comment by morloderex** [comment]
@mattstauffer Would it make sense to ask the consumer about what kind of stability package we should use, instead of "just" using the lastest tag given the fact that the lastest tag could be a "alpha", "beta" or anyother kind of non versioned tag?

**Comment by mattstauffer** [comment]
Good question. My inclination is to provide a "safe" default, probably non-beta (unless @josecanhelp suggests that's not the common action to take in the Docker world), and then remember people can always pass whatever tag they want.. and MAYYYBE we consider some sort of facility to let them list some tags or search tags? Not sure about that last part.

**Comment by edalzell** [comment]
Related: https://github.com/tighten/takeout/pull/216#issuecomment-812804285.

Pulling the 10 latest, in Postgres' case doesn't work.

**Comment by haneez** [comment]
Yes please. Please implement a way to default to LTS, Stable, etc.

**Comment by mattstauffer** [comment]
I believe we're *not* showing beta. If anyone is seeing betas pulled in, please create a new issue. Thanks!
