### ISSUE TITLE
Mongo install fails

### ISSUE THREAD

**Issue by morrislaptop** [tighten/takeout#251]
```
 OUT  4.2.16-rc0-nanoserver-1809: Pulling from library/mongo
 ERR  no matching manifest for linux/arm64/v8 in the manifest list entries
Enabling mongo...

 ERR  Unable to find image 'mongo:4.2.16-rc0-nanoserver-1809' locally
 ERR  4.2.16-rc0-nanoserver-1809: Pulling from library/mongo
 ERR  docker: no matching manifest for linux/arm64/v8 in the manifest list entries.
 ERR  See 'docker run --help'.

Failed installing mongo
```

**Comment by morrislaptop** [comment]
This might be m1 related actually :/

**Comment by mechelon** [comment]
I think I encountered a similar problem while installing MeiliSearch on M1.

`ERR  WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`

It says Services enabled, but the container is not started.
Maybe adding a --platform option could work? 🤔

**Comment by josecanhelp** [comment]
@morrislaptop Thanks for bringing this up. It is an issue with arm incompatibility, but it's also an issue with how we try to detect the best "latest" tag. Right now, we don't take the host machine's chip architecture into account when finding the best "latest" tag to use. However, there is a tag for mongo that is compatible with m1 arm architecture right now.

When you enable the mongo container and the prompt asks which version you would like to use. Try entering `5` and it should pull down an image for you that works.
