### ISSUE TITLE
Error The provided cwd "" does not exist. (In Process.php line 347)

### ISSUE THREAD

**Issue by Ashraam** [tighten/takeout#252]
Hi,

Since this morning I've got this error when I try to use takeout start or takeout start --all.

It was working good on friday and no update were applied to the system.

The takeout command works and list available commands.

My PHP version is 7.4.22
Composer: 2.0.14
Takeout version: 1.8.11

**Comment by mattstauffer** [comment]
@Ashraam Are you still seeing this problem? Thanks!

**Comment by Ashraam** [comment]
Sorry for not closing the issue, it started to work normally the next morning (still don't know why, I rebooted the system multiple times).

Anyway thank you for this magical package @mattstauffer  !

**Comment by mattstauffer** [comment]
@Ashraam So glad to hear it! no worries at all, and thanks for your kind words!
