### ISSUE TITLE
Feature Request - Websocket service(s)

### ISSUE THREAD

**Issue by willvincent** [tighten/takeout#267]
There are two opensource websocket solutions that provider Pusher compatible websocket servers available, and [mentioned in the official Laravel docs](https://laravel.com/docs/8.x/broadcasting#pusher-compatible-open-source-alternatives). 

[Laravel-Websockets](https://beyondco.de/docs/laravel-websockets/getting-started/introduction) is installable as a standard Laravel package, so not relevant here.  However, [soketi](https://rennokki.gitbook.io/soketi-docs) was also recently added, and is available as a docker image, so probably makes sense to include.

**Comment by ahoiroman** [comment]
Yeah, I am really looking forward to an integration of soketi. So +1 and thanks for your work, @tighten.
