### ISSUE TITLE
"The provided cwd "" does not exist" error

### ISSUE THREAD

**Issue by mattstauffer** [tighten/takeout#281]
![image](https://user-images.githubusercontent.com/151829/156846374-2067f839-401a-446f-ad2e-abab2e43a9c6.png)

Error provided in #260 by @priithansen.

Opening a separate issue to move it out of that issue.

I can't reproduce but I'm on the machine that built it so trying to figure out what might be happening.

**Comment by bandgeekndb** [comment]
Unable to reproduce with v2.0.2 on Ubuntu 20.04 (Windows WSL2). I'm able to list, start, and stop containers without issue.

**Comment by priithansen** [comment]
Yes must have been something weird in limbo on my machine as 2.0.2 seems to be now working fine here also!

**Comment by mattstauffer** [comment]
OH. Easy enough. haha. Thanks!
