### ISSUE TITLE
enable and start use different parameters 

### ISSUE THREAD

**Issue by njames** [tighten/takeout#284]
Start needs a container image but enable needs a service name - any chance these can be `consistantified*`?

 takeout start mysql8.0

 ERR  Docker container mysql8.0 not found.

 takeout start ce960ac00aad
 OUT  ce960ac00aad

takeout disable postgres
 OUT  3dbce21477fd
Disabling Service...: ✔

`* made consistent ;)`

**Comment by njames** [comment]
and it would be great to have the output of `takeout start --all` provide aliases as part of DX 

``` 
(base) 09:02:40 ~$ takeout start --all
 OUT  ce960ac00aad
 OUT  8216bab33229
 OUT  4d051a456984
```

Just a thought, a nice to have.

**Comment by tonysm** [comment]
I like the suggestion of accepting the service names as possible values to the start/stop commands. That's definitely some UX improvements, imo.

Changing the output is a bit tricky, I think. What we see there in the `takeout stop` command output is the same output provided by the `docker stop` command. I agree we could add more info to it, just not sure how _easy_ that would be.

I'm taking a look at it.

**Comment by njames** [comment]
Hey Tony I looked more at the start output and you are right - it is just the docker output so changing that is tricky. 

I have just started doing a list after my start. 

Ie `takeout start --all; takeout list;`
