### ISSUE TITLE
SQL Server on Mac M1 fails to start

### ISSUE THREAD

**Issue by morrislaptop** [tighten/takeout#293]
Fails with the message: ` ERR  WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`

If it helps, the following command works `docker run -e "ACCEPT_EULA=1" -e "MSSQL_SA_PASSWORD=MyPass@word" -e "MSSQL_PID=Developer" -e "MSSQL_USER=SA" -p 1433:1433 -d --name=sql mcr.microsoft.com/azure-sql-edge`

Taken from https://medium.com/geekculture/docker-express-running-a-local-sql-server-on-your-m1-mac-8bbc22c49dc9

**Comment by tonysm** [comment]
@morrislaptop I've tested out that image and was able to get it running on my M1 and on my Linux laptop (same image). But is this new image fully compatible with the previous one?

For reference, I've created a branch called `fix/tm-mssql-arm` and here's the [diff](https://github.com/tighten/takeout/compare/main...fix/tm-mssql-arm).

**Comment by tcampbPPU** [comment]
> Taken from https://medium.com/geekculture/docker-express-running-a-local-sql-server-on-your-m1-mac-8bbc22c49dc9
Damn tried to follow the steps from this post and I am unable to get the database to run

**Comment by tcampbPPU** [comment]
> Damn tried to follow the steps from this post and I am unable to get the database to run

idk why wasn't able to get it to pull image correclty but doing this with docker itself is working:
```bash
docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=useA$strongPas1337' -p 1433:1433 -v mssql_data:/var/opt/mssql --name sql1 -d mcr.microsoft.com/azure-sql-edge:latest
```
