### ISSUE TITLE
PHP error in phar

### ISSUE THREAD

**Issue by MarceauKa** [tighten/takeout#296]
Hi, after removing then reinstalling takeout I got this error when I try to run `takeout`

```php
Parse error: syntax error, unexpected token ")" in phar:///Users/username/.composer/vendor/tightenco/takeout/builds/takeout/vendor/symfony/finder/Finder.php on line 588
```

Takeout: 2.1
Composer: 2.3.5
PHP: 8.0.21

**Comment by mattstauffer** [comment]
Thanks! Closed in 2.1.1

**Comment by subdesign** [comment]
Hi, I have the same error, but I have 2.2.0 installed! 
PHP 8.0.19
Comp: 2.3.5

<img width="1351" alt="Screenshot 2022-12-02 at 11 15 47" src="https://user-images.githubusercontent.com/691695/205270187-c03dbf81-04f6-4c28-98dd-ce38ea253efe.png">

**Comment by therobfonz** [comment]
Also seeing this same error on 2.3.0 and PHP 8.0.26. 

![Screenshot 2023-01-03 at 6 05 02 AM](https://user-images.githubusercontent.com/35386780/210345386-7efb4147-8e48-4e35-a016-cafb77e302fa.png)

**Comment by tonysm** [comment]
Taking a look at this...

**Comment by tonysm** [comment]
So, packagist says we support PHP 8.0. To do that, we need to be on that version when developing, or at least at the time we're building the phar file and also when installing the Composer dependencies. Installing the Composer dependencies from a higher PHP version may get dependencies that are not compatible with PHP 8.0.

**Comment by tonysm** [comment]
Just tagged a new patch release [v2.3.1](https://github.com/tighten/takeout/releases/tag/v2.3.1) with the fix for this.
