### ISSUE TITLE
PHP Error in Phar

### ISSUE THREAD

**Issue by devsquad-alvaro-meireles** [tighten/takeout#297]
`PHP Parse error:  syntax error, unexpected 'static' (T_STATIC) in phar:///home/user/.config/composer/vendor/tightenco/takeout/builds/takeout/vendor/symfony/string/UnicodeString.php on line 44`

PHP: 7.4
Linux: Linux Mint 20.2
Composer: 2.3.10

**Comment by mattstauffer** [comment]
@devsquad-alvaro-meireles This is fixed in v2.1.1, _but_ Takeout no longer officially supports PHP 7.4, so I can't promise you won't have other issues.
