### ISSUE TITLE
Failed installing mongo

### ISSUE THREAD

**Issue by wrtisans** [tighten/takeout#306]
hello, i've problems with mongo db

i got this error 

 OUT  6.0.3-nanoserver-ltsc2022: Pulling from library/mongo
 ERR  no matching manifest for linux/amd64 in the manifest list entries
Enabling mongo...

 ERR  Unable to find image 'mongo:6.0.3-nanoserver-ltsc2022' locally
 ERR  6.0.3-nanoserver-ltsc2022: Pulling from library/mongo
 ERR  docker: no matching manifest for linux/amd64 in the manifest list entries.
 ERR  See 'docker run --help'.

Failed installing mongo

Docker version 20.10.21, build baeda1f

mac os ventura 13.1 (intel)
Takeout v2.2.0

**Comment by tonysm** [comment]
Taking a look at this.

**Comment by tonysm** [comment]
Hey @mrailton 

We have tested this on a M1 mac (Ventura 13.0.1), on a Linux laptop (Intel), and on an Intel Mac (also on Ventura 13.0.1). It worked on all of them.

Can you provide more info here? Were you trying to enable mongo with the default settings? Was it your first time enabling mongo? Can you share the full command and output you used?

**Comment by tonysm** [comment]
Hey @wrtisans 

We have tested this on a M1 mac (Ventura 13.0.1), on a Linux laptop (Intel), and on an Intel Mac (also on Ventura 13.0.1). It worked on all of them.

Can you provide more info here? Were you trying to enable mongo with the default settings? Was it your first time enabling mongo? Can you share the full command and output you used?
