### ISSUE TITLE
ghcr.io containers

### ISSUE THREAD

**Issue by necrogami** [tighten/takeout#310]
Currently this only handles docker hub images, while working on a potential pr for singlestore i ran into some issues since this container is not on docker hub.

The first wall i ran into is from `DockerTags.php` as it assumes docker hub registry, I can add an option to the function to be able to handle ghcr.io containers however to pull the tags list from github requires a github token. Do you have any ideas on how you want this handled?

**Comment by tonysm** [comment]
Hey @necrogami 

We have other services which use a different registry, such as [MsSql](https://github.com/tighten/takeout/blob/main/app/Services/MsSql.php) or [Soketi](https://github.com/tighten/takeout/blob/main/app/Services/Soketi.php), for instance. Are those useful to you?

I'm closing the issue as I think those should serve as references, but pls feel free to reopen it if you think those are not very helpful in your situation.

**Comment by necrogami** [comment]
Any suggestions for the tagslist class? As to get the tags list it requires a github token:

https://github.com/orgs/community/discussions/26279
