### ISSUE TITLE
PHP 8.2 comatibility

### ISSUE THREAD

**Issue by TiiFuchs** [tighten/takeout#314]
I get this error message using PHP 8.2 when just entering `takeout`:

```
Deprecated: Return type of HumbugBox3130\KevinGH\RequirementChecker\RequirementCollection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar://[...]/.composer/vendor/tightenco/takeout/builds/takeout/.box/src/RequirementCollection.php on line 12
```

I guess that's a PHP compatibility problem.

I can't find any information on the README which PHP versions are officially supported.

**Comment by scheMeZa** [comment]
@vblinden is correct.
I can confirm as I am using takeout with PHP 8.2

**Comment by tonysm** [comment]
Hey @TiiFuchs 

I'm using Takeout (v2.5.0 at the time of writing) with PHP 8.2.6. What version of Takeout are you using? I think the suggestion from @vblinden should fix it.

I'm gonna close the issue, but pls feel free to reopen it and leave a comment if that doesn't work for you.

**Comment by cheesegrits** [comment]
@tonysm maybe update the installation instructions?  I just had the same issue, followed the instructions, the composer install command given installs 1.x.  Maybe give a more specific example for folk with PHP 8.2?

**Comment by tonysm** [comment]
@cheesegrits we're working on something that should fix issues like this one. See #326 if you're curious.
