### ISSUE TITLE
After updating Mac OS, containers are missing

### ISSUE THREAD

**Issue by roarkmccolgan** [tighten/takeout#316]
Hi All.

I hope you're well.

I updated my OS and docker and Takeout were still installed and working but when i ran ```takeout start``` it said 'not takout containers to start'

Is there a way I can restore them? Where are they located when created?

Thanks so much!

**Comment by tonysm** [comment]
Hey @roarkmccolgan 👋🏼 

What do you see when you run `docker ps -a`? If you still have stopped containers, they should show up. If they don't, I'm afraid you will not be able to recover them. If you've mapped the container's to any folder, you should still be able to see the files where you mapped it in your filesystem.

**Comment by tonysm** [comment]
Closing this one. If you have any more hints, please let us know!

Btw, even if the container is gone, the Docker Volume is persisted on your host machine, so you can spin up a new container using that volume and it should work.
