### ISSUE TITLE
takeout enable and disable commands are missing

### ISSUE THREAD

**Issue by iamejaaz** [tighten/takeout#320]
![image](https://github.com/tighten/takeout/assets/67804911/dc7d97e7-3592-472f-92ce-fd83c2d45fd5)
I am trying to create a container but says `Error: command enable not found`

**Comment by tonysm** [comment]
@iamejaaz Looks like you installed an alpha version we were exploring of [Takeout in Node.js](https://www.npmjs.com/package/@tighten/takeout). That's not the official version, so not all commands were implemented there (as I said, we were exploring that). Pls, use the [PHP version using Composer](https://packagist.org/packages/tightenco/takeout).
