### ISSUE TITLE
use of MySql 8.2 and 8.0.35 -  official mysql docker hub image 

### ISSUE THREAD

**Issue by bnaydenov** [tighten/takeout#329]
Currently MySql service [https://github.com/tighten/takeout/blob/main/app/Services/MySql.php](https://github.com/tighten/takeout/blob/main/app/Services/MySql.php) uses mysql docker hub image from [https://hub.docker.com/r/mysql/mysql-server/](https://hub.docker.com/r/mysql/mysql-server/) which for the last time is upgraded more then 1 year go and does not include newly released MySql `8.2`. Last version available is  there is`8.0.32`

There is official mysql docker image location [https://hub.docker.com/_/mysql](https://hub.docker.com/_/mysql) which is maintained by [the Docker Community and the MySQL Team](https://github.com/docker-library/mysql) and is updated regularly and having all latest version like `8.2` and `8.0.35`.

My suggestion is to change MySql service [https://github.com/tighten/takeout/blob/main/app/Services/MySql.php](https://github.com/tighten/takeout/blob/main/app/Services/MySql.php) to use this official image which is updated more regularly [https://hub.docker.com/_/mysql](https://hub.docker.com/_/mysql).

i will provide PR

**Comment by vintagesucks** [comment]
[`mysql:8.0.34`](https://hub.docker.com/_/mysql/tags?page=1&name=8.0.34) and newer includes support for `linux/arm64`, so switching to [`mysql:8.0`](https://hub.docker.com/_/mysql/tags?page=1&name=8.0) should no longer be a problem.

I updated the image inside a MySQL container created by Takeout on a M1 MacBook Air from `mysql/mysql-server:8.0` to `mysql:8.0` to update from `8.0.32` to `8.0.35` and everything seems to be running fine.
