### ISSUE TITLE
Unable to install mongo

### ISSUE THREAD

**Issue by rognales** [tighten/takeout#337]
My machine is MBP M1 pro and installed version
```console
php -v
PHP 8.1.27 (cli) (built: Dec 19 2023 20:35:55) (NTS)

composer global show tightenco/takeout | grep versions
Changed current directory to /Users/rognales/.composer
versions : * v2.6.0
```
When i issue `takeout enable mongo --default`, it will failed with this

```console
takeout enable mongo --default

Warning: Module "imap" is already loaded in Unknown on line 0
Downloading docker image...

 OUT  7.0.8-nanoserver-ltsc2022: Pulling from library/mongo
 ERR  no matching manifest for linux/arm64/v8 in the manifest list entries
Enabling mongo...

 ERR  Unable to find image 'mongo:7.0.8-nanoserver-ltsc2022' locally
 ERR  7.0.8-nanoserver-ltsc2022: Pulling from library/mongo
 ERR  docker: no matching manifest for linux/arm64/v8 in the manifest list entries.
 ERR  See 'docker run --help'.

Failed installing mongo  
```

if i try to pass custom image `arm64v8/mongo` when it prompted for tags, it still down the same image as above

1. Is M1 not supported? But I can download the image manually `docker pull arm64v8/mongo`.
2. What is the correct way to pass custom image?

**Comment by rognales** [comment]
it is pulling this image https://hub.docker.com/layers/library/mongo/7.0.8-nanoserver-ltsc2022/images/sha256-5623c8cd57549465794442099ddda3237e5043a6d21af96128dcef4bae2d6f5f?context=explore

<img width="1302" alt="image" src="https://github.com/tighten/takeout/assets/28396330/51d93a49-886d-45f4-b28d-9793fd32b6b1">

Perhaps it wrongly detect which arm variant?

**Comment by rognales** [comment]
I managed to get it to run if I passed `jammy` as tag

**Comment by tonysm** [comment]
Hey, M1 Mac is supported. I noticed a similar issue with the MySQL service pulling the `8.4.0-oraclelinux8` instead of just `8.4.0`, for instance. That has to do with the tagging sort, I believe.
