### ISSUE TITLE
On multiline output, add indentation for later lines

### ISSUE THREAD

**Issue by mattstauffer** [tighten/takeout#59]
![image](https://user-images.githubusercontent.com/151829/91214085-97ad4800-e6e0-11ea-8bd0-c0cff34f409d.png)

In the above image, we would want to indent the "Pulling" lines to match the other lines' start points.

**Comment by thinkstylestudio** [comment]
@mattstauffer just a reminder, you took care of this in the bit you submitted here https://github.com/tighten/takeout/commit/c2ffacb5f84961aca4a91b20aa5b359bf88bd732 @josecanhelp

**Comment by josecanhelp** [comment]
Thanks @thinkstylestudio!

**Comment by thinkstylestudio** [comment]
Any time. :)
