### ISSUE TITLE
Consider custom images that are managed by the user or passing through custom config files during the run process.

### ISSUE THREAD

**Issue by josecanhelp** [tighten/takeout#91]
Example:
We currently offer elasticsearch, but some users may want to enable Xpack by passing through a custom `elasticsearch.yml` file.

Different Methods to solve this:
- include a volume flag to pass a file into the container when bringing it up via the run command
- allow users to manage Dockerfiles locally that can be used to build custom images and run them via takeout

**Comment by mattstauffer** [comment]
Super interesting. I think I'm most interested in the custom dockerfiles, but what do you think the preferred option is when someone really just wants to make a small config?

**Comment by josecanhelp** [comment]
It really depends on the image itself. Sometimes they accept arguments/flags, sometimes you literally have to build your own custom image. 

A thought crossed my kind that we could (if needed) generate a dockerfile based on prompts from takeout.
