### ISSUE TITLE
Allow for `null` password for MySQL

### ISSUE THREAD

**Issue by mattstauffer** [tighten/takeout#96]
Use `MYSQL_ALLOW_EMPTY_PASSWORD` instead of `MYSQL_ROOT_PASSWORD` or whatever the other is

```bash
docker run -d --name "TO--mysql--5.7" -e MYSQL_ALLOW_EMPTY_PASSWORD="yes" -p 3306:3306 -v mysql_57_data:/var/lib/mysql library/mysql:5.7
```

**Comment by josecanhelp** [comment]
Should we still default to "password" or default to an empty password?

If we default to "password", instead of adding another prompt, should we allow users to enter "none" and we can check for that string and add the `MYSQL_ALLOW_EMPTY_PASSWORD` flag?
